### ISSUE TITLE
Hard coded indigo with a "g"

### ISSUE THREAD

**Issue by rafagsiqueira** [indico/indico-containers#11]
Hello,
Thank you for working on dockerizing indico. While testing it here in our docker swarm I ran into the following problem while running indico-celery:
```Cannot connect to redis://indigo-celery:6379/0```
Note the "g" in indigo.

Even though I am passing the right environmental variables into docker, this seems to be hard coded. Please note the output of $> env

```
REDIS_CACHE_URL=redis://indico-redis:6379/1
CELERY_BROKER=redis://indico-redis:6379/0
```
Thank you for your help and initiative!

**Comment by ThiefMaster** [comment]
I [can't find](https://github.com/indico/indico-containers/search?q=CELERY_BROKER&unscoped_q=CELERY_BROKER) any occurrence of this. Are you sure this is not a typo somewhere in your local clone of the files from this repo? Try searching in your local files for `indigo-celery` and then `git blame` that file to see where it's coming from.

**Comment by rafagsiqueira** [comment]
You were correct. The issue was very hard to find because the typo was nowhere in any of my configuration files. It was actually stored in my docker swarm as a docker config. After removing the docker config and creating another one it worked. Thank you very much for your help and such a prompt response!
