### ISSUE TITLE
No permissions to create extension "unaccent"

### ISSUE THREAD

**Issue by rafagsiqueira** [indico/indico-containers#12]
Hello!
Thank you again for the initiative.
While testing indico on our Docker Swarm I ran into the following problem, when running run_indico.sh:
```Preparing DB...
Using external database...
ERROR:  permission denied to create extension "unaccent"
HINT:  Must be superuser to create this extension.
ERROR:  permission denied to create extension "pg_trgm"
HINT:  Must be superuser to create this extension.
```
I had to manually run
```alter role indico superuser;```
In postgres container, as admin. 
Thank you for your help and initiative!

**Comment by ThiefMaster** [comment]
the indico user should not have superuser privs (that's the DB equivalent of running your webapp as root). I'd rather remove [these two lines](https://github.com/indico/indico-containers/blob/master/indico/worker/run_indico.sh#L19-L20) and mention that the extensions need to be created manually using a postgres superuser.

**Comment by rafagsiqueira** [comment]
I agree with you, but maybe the solution could be implemented on the docker-compose, otherwise a simple docker-compose up does not work. One solution could be to pass a run script to postresql entrypoint.

**Comment by rafagsiqueira** [comment]
By using the postgres image instead of the centos/postgresql-96-centos7 suggested in your docker-compose, you can pass an init script like this by copying the file to: 
`/docker-entrypoint-initdb.d/init-user-db.sh`
Here is how the script should go:
```
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "indico" <<-EOSQL
    CREATE EXTENSION unaccent;
    CREATE EXTENSION pg_trgm;
EOSQL
```
What do you think about this solution?

**Comment by ThiefMaster** [comment]
I like it - but don't you also need to create the db first?
