### ISSUE TITLE
Update docker image/upload Dockerfile?

### ISSUE THREAD

**Issue by Eothred** [indico/indico-containers#17]
First of all, thanks for providing this very useful test environment! Not sure if this is just me not understanding docker-compose properly, but I get the impression that the docker-web defined in the yaml is pulled from Docker hub, which is still on version 2.1.3? When I start this one at least it warns me that I am on an old version. Is the Dockerfile for this image available somewhere else perhaps? Alternatively, could you add it somewhere suitable and/or update the image on Docker hub?

**Comment by mic4ael** [comment]
Hey, thanks for reminding us about this. We have updated the image on DockerHub and I will soon create a PR with changes to the `docker-compose.yml`. These changes will make sure that you can run `docker-compose` with the latest Indico image.
