### ISSUE TITLE
Help with email encryption

### ISSUE THREAD

**Issue by phamminhtris** [indico/indico-containers#19]
Hi, sorry if this question is too trivial. I am trying to connect my indico instance to a gmail account (we don't host an email server). However, even if I set 

```SMTP_USE_TLS=True```

The connection to email server still seem to be served over http (gmail complains and does not allow Indico to connect to the service). Any help is appreciated. Thanks

**Comment by ThiefMaster** [comment]
Gmail is not really suitable for this usecase (unless, maybe, you use google apps or whatever the enterprise version is called).

Also, Indico uses SMTP to connect to an email server - there is absolutely no HTTP involved. If you enable `SMTP_USE_TLS`, then STARTTLS will be used to switch to an encrypted connection.
