### ISSUE TITLE
Python error when installing

### ISSUE THREAD

**Issue by PraveenAlexis** [indico/indico-containers#23]
print 'Upgrading existing etc/indico.conf...'
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Upgrading existing etc/indico.conf...')?

**Comment by ThiefMaster** [comment]
sounds like it's using a highly outdated version of indico. please provide more details including the full shell output and the command you executed.

**Comment by PraveenAlexis** [comment]
i just ran docker-compose up

`+ pip download --no-deps -d /tmp/indico-pip indico
Collecting indico
  Downloading indico-1.2.2.tar.gz (54.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-download-wmjiygm5/indico_1aa4cb797d874c34908a76f50b073db2/setup.py'"'"'; __file__='"'"'/tmp/pip-download-wmjiygm5/indico_1aa4cb797d874c34908a76f50b073db2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-l0yzyhtq
         cwd: /tmp/pip-download-wmjiygm5/indico_1aa4cb797d874c34908a76f50b073db2/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-wmjiygm5/indico_1aa4cb797d874c34908a76f50b073db2/setup.py", line 219
        print 'Upgrading existing etc/indico.conf...'
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Upgrading existing etc/indico.conf...')?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ef/07/b8307e72a251e6080fdadf9aa8fea91d11f4a7d426aac40531337386dcf6/indico-1.2.2.tar.gz#sha256=b7155aadd1d53f41e9ddec2b76e227aa77331c41def9df02d053162c3f4f869c (from https://pypi.org/simple/indico/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading indico-1.2.1.tar.gz (54.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-download-wmjiygm5/indico_9254c7dc22364a2581932ca806a01fc2/setup.py'"'"'; __file__='"'"'/tmp/pip-download-wmjiygm5/indico_9254c7dc22364a2581932ca806a01fc2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xrjrdwvd
         cwd: /tmp/pip-download-wmjiygm5/indico_9254c7dc22364a2581932ca806a01fc2/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-wmjiygm5/indico_9254c7dc22364a2581932ca806a01fc2/setup.py", line 219
        print 'Upgrading existing etc/indico.conf...'
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Upgrading existing etc/indico.conf...')?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/13/de/85be8c2a5c40bfe0bee89735d07b91d2aa1ee0587a3a066feb8dc3fdf522/indico-1.2.1.tar.gz#sha256=0bbefe5678623872d5fb30fef0c95cbc1d894388ba40abe1f29502c750885661 (from https://pypi.org/simple/indico/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement indico (from versions: 1.2.1rc5, 1.2.1rc7, 1.2.1rc9, 1.2.1rc10, 1.2.1rc11, 1.2.1, 1.2.2rc1, 1.2.2)
ERROR: No matching distribution found for indico
ERROR: Service 'indico-static' failed to build: The command '/bin/sh -c set -ex &&         mkdir /tmp/indico-pip &&         pip install -U pip &&         pip download --no-deps -d /tmp/indico-pip indico &&         unzip /tmp/indico-pip/indico-*.whl -d /srv/ 'indico/web/static/*' &&         rm -rf /tmp/indico-pip' returned a non-zero code: 1`

**Comment by ThiefMaster** [comment]
Ah I see, looks like the `nginxinc/nginx-unprivileged:stable-alpine` image has only Python 3, but we have no official Indico release for Python 3 yet... I just fixed it.
