### ISSUE TITLE
no amd64 image for indico 3.1 ? 

### ISSUE THREAD

**Issue by ednxzu** [indico/indico-containers#25]
Hello, 
I noticed there is no amd64 image for indico version 3.1. The only one listed on docker hub is the arm64 one.
Is this by design or is it a miss ?

Best,

**Comment by ThiefMaster** [comment]
that seems like a mistake, probably due to the fact that the developer building the images has an M1 mac now...

@plourenco ^

**Comment by plourenco** [comment]
Yes, exactly that. Thanks for the heads-up! It's updated by now.
