### ISSUE TITLE
Help wanted: clarify deployment for production

### ISSUE THREAD

**Issue by ClundXIII** [indico/indico-containers#27]
Hello,

from the Readme file:

> ATTENTION: DO NOT use this in production as it is. There are important things missing, such as HTTPS support.

Apart from putting an HTTPs reverse proxy in front of the application, are there any other things one should do?

The volumes with persistent data seems all to be here (although I will probably map them all to folders on my drive).

**Comment by ThiefMaster** [comment]
I think the warning is a bit obsolete. HTTPS support indeed belongs outside these containers, and as long as you properly persist data (DB + archive folder) it should be alright.

**Comment by ClundXIII** [comment]
Thanks a lot :)
