### ISSUE TITLE
Docker container not updated consistently with new Indico new releases

### ISSUE THREAD

**Issue by lavaux** [indico/indico-containers#30]
Hi,

It seems that the docker container version has been updated two months ago and is lagging two versions behind indico. Maybe that should be automated?
![image](https://github.com/indico/indico-containers/assets/7413739/c31cba4c-5112-4b6e-be06-7bf7b13b664e)

**Comment by ThiefMaster** [comment]
I fully agree that we should automate this now that we build and publish releases via CI anyway!

**Comment by ThiefMaster** [comment]
We now have CI to build and publish #32, and I just used it to publish the image for the latest v3.2.7 release to Docker Hub.

**Comment by lavaux** [comment]
Hello,

Version 3.2.8 was never published on docker, though it has been available on GitHub for 2 months now. I suppose that the trigger missed the new indico release for the last two months?

**Comment by ThiefMaster** [comment]
Indeed, forgot to create the tag. Triggered the build now.

**Comment by lavaux** [comment]
Could we tag 3.3.1 now? Thanks!

**Comment by ThiefMaster** [comment]
We have not fully updated the docker setup for 3.3 yet. So we won't *immediately* publish the Docker image for 3.3 but rather once it's ready.

**Comment by lavaux** [comment]
As this issue is stale, do you need help for a specific place? Or just try to build the containers? Or Do we need to ensure that the database migration goes well?

**Comment by ThiefMaster** [comment]
Building the images from #28 will likely work (there are some open discussion points in there, especially around DB upgrades). The DB migration just requires running `indico db upgrade` so a simple `docker exec ...` inside the container would probably do the job.
